import pandas as pd
import get_stock_data
import datetime

class Portfolio(object):

    def __init__(self, start, end, stock_list, invested_cap):
        self.start = start
        self.end = end
        self.stock_list =


    def rebalance(rebalance_date):
        """Use prices at close of 'rebalance_date', or closest prior day"""
        pass

    def get_total_return():
        """Total return, when measuring performance, is the actual rate of return of an
        investment or a pool of investments over a given evaluation period. Total return
        includes interest, capital gains, dividends and distributions realized over a
        given period of time."""
        pass

    def get_price_return():
        """The price return is the rate of return on an investment portfolio,
        where the return measure takes into account only the capital appreciation of
        the portfolio, while the income generated by the assets in the portfolio,
        in the form of interest and dividends, is ignored."""
        pass


if __name__ == '__main__':

    # File with list of stocks
    stock_file = 'djt_components.csv'

    # Set the Start and End date ranges
    start = datetime.datetime(2007, 1, 1)
    end = datetime.datetime(2016, 12, 31)

    # Get historical stock data
    d = get_stock_data.get_data(stock_file, start, end)

    d.to_csv('master.csv')